In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
saas = pd.read_csv(r"E:\FunnelXray\data\processed\merged_saas.csv")

In [3]:
saas.head()

,user_id,name,email,signup_date,country,device,transaction_id,amount,payment_method,payment_status,transaction_time,event_id,event_type,event_time,product_id,product_name,category,price
0,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3656,add_to_cart,2023-10-18,P1,Free Plan,subscription,0
1,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3219,click,2023-07-04,P10,API Access,platform,18
2,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3218,click,2023-11-13,P5,Analytics Dashboard,feature,15
3,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2049,view,2023-10-11,P5,Analytics Dashboard,feature,15
4,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2048,view,2023-12-20,P1,Free Plan,subscription,0

In [4]:
saas.describe()

            amount        price
count  9391.000000  9763.000000
mean     18.053562    16.962102
std      17.278376    16.172244
min       0.000000     0.000000
25%       0.000000     0.000000
50%      15.000000    15.000000
75%      25.000000    25.000000
max      60.000000    60.000000

In [5]:
saas.info()

<class 'pandas.DataFrame'>
RangeIndex: 9763 entries, 0 to 9762
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           9763 non-null   str
 1   name              9763 non-null   str
 2   email             9763 non-null   str
 3   signup_date       9763 non-null   str
 4   country           9763 non-null   str
 5   device            9763 non-null   str
 6   transaction_id    9391 non-null   str
 7   amount            9391 non-null   float64
 8   payment_method    9391 non-null   str
 9   payment_status    9391 non-null   str
 10  transaction_time  9391 non-null   str
 11  event_id          9763 non-null   str
 12  event_type        9763 non-null   str
 13  event_time        9763 non-null   str
 14  product_id        9763 non-null   str
 15  product_name      9763 non-null   str
 16  category          9763 non-null   str
 17  price             9763 non-null   int64
dtypes: float64(1), int64(1), str(16)
memory usage: 1.3 MB

In [6]:
saas.columns

Index(['user_id', 'name', 'email', 'signup_date', 'country', 'device',
       'transaction_id', 'amount', 'payment_method', 'payment_status',
       'transaction_time', 'event_id', 'event_type', 'event_time',
       'product_id', 'product_name', 'category', 'price'],
      dtype='str')

In [7]:
saas.isnull().value_counts

<bound method DataFrame.value_counts of       user_id   name  email  signup_date  country  device  transaction_id  \
0       False  False  False        False    False   False            True
1       False  False  False        False    False   False            True
2       False  False  False        False    False   False            True
3       False  False  False        False    False   False            True
4       False  False  False        False    False   False            True
...       ...    ...    ...          ...      ...     ...             ...
9758    False  False  False        False    False   False           False
9759    False  False  False        False    False   False           False
9760    False  False  False        False    False   False           False
9761    False  False  False        False    False   False           False
9762    False  False  False        False    False   False           False

      amount  payment_method  payment_status  transaction_time  event_id  \
0       True            True            True              True     False
1       True            True            True              True     False
2       True            True            True              True     False
3       True            True            True              True     False
4       True            True            True              True     False
...      ...             ...             ...               ...       ...
9758   False           False           False             False     False
9759   False           False           False             False     False
9760   False           False           False             False     False
9761   False           False           False             False     False
9762   False           False           False             False     False

      event_type  event_time  product_id  product_name  category  price
0          False       False       False         False     False  False
1          False       False       False         False     False  False
2          False       False       False         False     False  False
3          False       False       False         False     False  False
4          False       False       False         False     False  False
...          ...         ...         ...           ...       ...    ...
9758       False       False       False         False     False  False
9759       False       False       False         False     False  False
9760       False       False       False         False     False  False
9761       False       False       False         False     False  False
9762       False       False       False         False     False  False

[9763 rows x 18 columns]>

In [8]:
saas.nunique()

user_id              800
name                  64
email                800
signup_date          334
country                5
device                 4
transaction_id      1931
amount                 9
payment_method         5
payment_status         3
transaction_time     363
event_id            3886
event_type             5
event_time           365
product_id            11
product_name          11
category               4
price                  9
dtype: int64

In [9]:
saas["user_id"].nunique()

800

In [10]:
saas["user_id"].nunique()

800

In [11]:
saas.index.nunique()

9763

In [12]:
saas.head()

,user_id,name,email,signup_date,country,device,transaction_id,amount,payment_method,payment_status,transaction_time,event_id,event_type,event_time,product_id,product_name,category,price
0,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3656,add_to_cart,2023-10-18,P1,Free Plan,subscription,0
1,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3219,click,2023-07-04,P10,API Access,platform,18
2,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3218,click,2023-11-13,P5,Analytics Dashboard,feature,15
3,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2049,view,2023-10-11,P5,Analytics Dashboard,feature,15
4,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2048,view,2023-12-20,P1,Free Plan,subscription,0

In [13]:
print("Total rows:", saas.shape[0])

Total rows: 9763

In [14]:
print("Unique users:", saas["user_id"].nunique())

Unique users: 800

In [15]:
print("Unique transactions:", saas["transaction_id"].nunique())

Unique transactions: 1931

In [16]:
print("Unique events:", saas["event_id"].nunique())

Unique events: 3886

In [17]:
saas.isnull().sum()

user_id               0
name                  0
email                 0
signup_date           0
country               0
device                0
transaction_id      372
amount              372
payment_method      372
payment_status      372
transaction_time    372
event_id              0
event_type            0
event_time            0
product_id            0
product_name          0
category              0
price                 0
dtype: int64

In [18]:
saas[saas["amount"] > 0]["user_id"].nunique()

659

In [19]:
saas[(saas["amount"] == 0) & (saas["transaction_id"].notna())]["user_id"].nunique()

373

In [20]:
saas[saas["transaction_id"].isna()]["user_id"].nunique()

74

In [21]:
paid = saas[saas["amount"] > 0]["user_id"].unique()
zero = saas[(saas["amount"] == 0) & saas["transaction_id"].notna()]["user_id"].unique()
none = saas[saas["transaction_id"].isna()]["user_id"].unique()

In [22]:
only_paid = len(set(paid) - set(zero))
only_paid

353

In [23]:
both = len(set(paid) & set(zero))
both

306

In [24]:
only_zero = len(set(zero) - set(paid))
only_zero

67

In [25]:
never = len(none)
never

74

In [26]:
saas[saas["amount"] > 0]["user_id"].unique()

<StringArray>
[  'U2',   'U5',   'U6',   'U7',   'U9',  'U10',  'U11',  'U12',  'U13',
  'U14',
 ...
 'U790', 'U791', 'U792', 'U793', 'U794', 'U795', 'U797', 'U798', 'U799',
 'U800']
Length: 659, dtype: str

In [27]:
saas[saas["amount"] > 0][["user_id", "name", "amount", "payment_method"]].drop_duplicates("user_id")

     user_id          name  amount payment_method
8         U2   Amit Sharma    12.0    net banking
31        U5  Sneha Kapoor    12.0    credit card
43        U6   Priya Mehta    25.0     no payment
54        U7   Rahul Mehta    10.0            upi
69        U9    Isha Verma    25.0     no payment
...      ...           ...     ...            ...
9716    U795  Sneha Kapoor    60.0    credit card
9727    U797    Amit Verma    15.0     debit card
9731    U798    Rahul Nair    10.0     no payment
9743    U799   Isha Sharma    25.0     debit card
9758    U800    Neha Singh    12.0    credit card

[659 rows x 4 columns]

In [28]:
saas["country"].value_counts()

country
india      3302
uk         1885
germany    1612
us         1577
unknown    1387
Name: count, dtype: int64

In [29]:
saas.drop_duplicates("user_id")["country"].value_counts()

country
india      270
uk         149
germany    139
us         121
unknown    121
Name: count, dtype: int64

In [30]:
saas.drop_duplicates("user_id")["device"].value_counts()

device
web        300
unknown    168
android    166
ios        166
Name: count, dtype: int64

In [31]:
saas[saas["device"] != "unknown"].drop_duplicates("user_id")["device"].value_counts()

device
web        300
android    166
ios        166
Name: count, dtype: int64

In [32]:
saas.drop_duplicates("user_id")["payment_status"].value_counts()

payment_status
success    623
failed      74
pending     29
Name: count, dtype: int64

In [33]:
saas.head()

,user_id,name,email,signup_date,country,device,transaction_id,amount,payment_method,payment_status,transaction_time,event_id,event_type,event_time,product_id,product_name,category,price
0,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3656,add_to_cart,2023-10-18,P1,Free Plan,subscription,0
1,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3219,click,2023-07-04,P10,API Access,platform,18
2,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3218,click,2023-11-13,P5,Analytics Dashboard,feature,15
3,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2049,view,2023-10-11,P5,Analytics Dashboard,feature,15
4,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2048,view,2023-12-20,P1,Free Plan,subscription,0

In [34]:
saas[saas["amount"] != 0].drop_duplicates("user_id")["payment_method"].value_counts()

payment_method
no payment     165
upi            133
debit card     127
net banking    124
credit card    110
Name: count, dtype: int64

In [35]:
saas[saas["payment_method"] == "no payment"]

,user_id,name,email,signup_date,country,device,transaction_id,amount,payment_method,payment_status,transaction_time,event_id,event_type,event_time,product_id,product_name,category,price
12,U2,Amit Sharma,user2@gmail.com,2023-10-28,germany,unknown,T1279,0.0,no payment,success,2023-08-02,E2512,view,2023-06-21,P5,Analytics Dashboard,feature,15
13,U2,Amit Sharma,user2@gmail.com,2023-10-28,germany,unknown,T1279,0.0,no payment,success,2023-08-02,E2511,view,2023-11-30,P10,API Access,platform,18
14,U2,Amit Sharma,user2@gmail.com,2023-10-28,germany,unknown,T1279,0.0,no payment,success,2023-08-02,E5,login,2023-09-03,P1,Free Plan,subscription,0
15,U2,Amit Sharma,user2@gmail.com,2023-10-28,germany,unknown,T1279,0.0,no payment,success,2023-08-02,E4,login,2023-01-16,P0,Unknown,unknown,0
43,U6,Priya Mehta,user6@gmail.com,2023-11-06,india,web,T710,25.0,no payment,failed,2023-04-27,E14,login,2023-07-15,P6,Email Automation,feature,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9748,U799,Isha Sharma,user799@gmail.com,2023-11-21,us,unknown,T1528,15.0,no payment,success,2023-08-13,E3949,purchase,2023-09-02,P4,Enterprise Plan,subscription,60
9749,U799,Isha Sharma,user799@gmail.com,2023-11-21,us,unknown,T1528,15.0,no payment,success,2023-08-13,E3619,add_to_cart,2023-07-04,P2,Basic Plan,subscription,10
9750,U799,Isha Sharma,user799@gmail.com,2023-11-21,us,unknown,T1528,15.0,no payment,success,2023-08-13,E3153,click,2023-02-09,P7,CRM Tool,feature,20
9751,U799,Isha Sharma,user799@gmail.com,2023-11-21,us,unknown,T1528,15.0,no payment,success,2023-08-13,E2346,view,2023-02-28,P5,Analytics Dashboard,feature,15
9752,U799,Isha Sharma,user799@gmail.com,2023-11-21,us,unknown,T1528,15.0,no payment,success,2023-08-13,E1625,login,2023-09-14,P8,AI Insights,feature,30

In [ ]:
saas["payment_method"] = saas["payment_method"].replace("no payment", "unknown_payment")

payment_method
True     7717
False    2046
Name: count, dtype: int64

In [41]:
saas[saas["payment_method"] != "unknown_payment"].drop_duplicates("user_id")["payment_method"].value_counts()

payment_method
net banking    176
upi            173
debit card     162
credit card    155
Name: count, dtype: int64

In [42]:
saas["amount"].mean()

np.float64(18.05356192098818)

In [43]:
saas["amount"].min()

np.float64(0.0)

In [44]:
saas["amount"].max()

np.float64(60.0)

In [45]:
saas["amount"].median()

np.float64(15.0)

In [49]:
saas["amount"].nlargest(5)

75     60.0
76     60.0
77     60.0
106    60.0
107    60.0
Name: amount, dtype: float64

In [50]:
saas.head()

,user_id,name,email,signup_date,country,device,transaction_id,amount,payment_method,payment_status,transaction_time,event_id,event_type,event_time,product_id,product_name,category,price
0,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3656,add_to_cart,2023-10-18,P1,Free Plan,subscription,0
1,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3219,click,2023-07-04,P10,API Access,platform,18
2,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E3218,click,2023-11-13,P5,Analytics Dashboard,feature,15
3,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2049,view,2023-10-11,P5,Analytics Dashboard,feature,15
4,U1,Karan Verma,user1@gmail.com,2023-04-22,uk,unknown,NaN,NaN,NaN,NaN,NaN,E2048,view,2023-12-20,P1,Free Plan,subscription,0

In [59]:
saas[(saas["amount"] == 0) & (saas["transaction_id"].notna())]["transaction_id"].nunique()

510